#ifndef MMAP_DEMO_CONSTANTS_HPP
#define MMAP_DEMO_CONSTANTS_HPP

enum {
    BIOME_DESERT,
    BIOME_SNOW,
    BIOME_GRASS,
    BIOME_ROCK,
    BIOME_WATER,
    BIOME_COUNT
};

enum {
    SITE_NOTHING,
    SITE_TREE,
    SITE_GOLD,
    SITE_MAGIC_ESSENCE,
    SITE_BERRY,
    SITE_DEER,
    SITE_STONE,
    SITE_FISH,
};

#endif //MMAP_DEMO_CONSTANTS_HPP
