#ifndef DEF_NETWORKING_CONSTANT_HPP
#define DEF_NETWORKING_CONSTANT_HPP

enum
{
    PACKET_SERVER_PUBLIC_KEY,         // Le serveur envoie sa clé publique
    PACKET_SETUP_ENCRYPTION_KEY,      // Le client envoie sa clé AES
    PACKET_SETUP_WORLD_SIZE,
    PACKET_SETUP_CHUNK,
    PACKET_SETUP_FLYWEIGHTS,
    PACKET_SPAWN_UNITS
};
#endif
