#ifndef MMAP_DEMO_CONSTANTS_TEXTURES_HPP
#define MMAP_DEMO_CONSTANTS_TEXTURES_HPP

enum {
    TEXTURE_TERRAIN,
    TEXTURE_NONE,
    TEXTURE_COMPARATOR
};

enum {
    PROGRAM_STANDARD,
    PROGRAM_BILLBOARD,
    PROGRAM_FULLSCREEN,
    PROGRAM_FOW
};

#endif //MMAP_DEMO_TEXTURES_HPP
